# MCPJungle Docker Compose configuration for individual users.
# Use this compose file if you want to run MCPJungle locally for your personal MCP management & Gateway.
# The mcpjungle server runs in development mode.
services:
  db:
    image: postgres:17
    container_name: mcpjungle-db
    environment:
      POSTGRES_USER: mcpjungle
      POSTGRES_PASSWORD: mcpjungle
      POSTGRES_DB: mcpjungle
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "PGPASSWORD=mcpjungle pg_isready -U mcpjungle" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mcpjungle:
    image: mcpjungle/mcpjungle:${MCPJUNGLE_IMAGE_TAG:-latest-stdio}
    container_name: mcpjungle-server
    environment:
      DATABASE_URL: postgres://mcpjungle:mcpjungle@db:5432/mcpjungle
      SERVER_MODE: ${SERVER_MODE:-development}
      OTEL_ENABLED: ${OTEL_ENABLED:-false}
      MCP_SERVER_INIT_REQ_TIMEOUT_SEC: ${MCP_SERVER_INIT_REQ_TIMEOUT_SEC:-10}
    ports:
      - "${HOST_PORT:-8080}:8080"
    volumes:
      # Mount host filesystem current directory to enable filesystem MCP server access
      - .:/host:ro
      # Other options:
      # - ${HOME}:/host/home:ro
      # - /tmp:/host/tmp:rw
    depends_on:
      db:
        condition: service_healthy
    restart: always

  localtunnel:
    image: node:alpine
    command: npx localtunnel --port 8080 --local-host mcpjungle
    depends_on:
      - mcpjungle
    restart: always

volumes:
  db_data:
